spring:
  rabbitmq:
    host: rabbitmq
    port: 5672
  sleuth:
    enabled: false
  collector:
    base-url: http://hap-zipkin-ui:9030/
  cloud:
    config:
      allowOverride: true
      failFast: true
      overrideNone: false
      overrideSystemProperties: false
