spring:
  datasource:
    url: jdbc:mysql://192.168.12.95:3307/hap_user_service?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: hapcloud
    password: handhand
  redis:
    host: 192.168.12.95
    port: 6377
  rabbitmq:
    host: 192.168.12.95
    port: 5672
  cloud:
    config:
      allowOverride: true
      failFast: true
      overrideNone: false
      overrideSystemProperties: false
  sleuth:
    integration:
      enabled: false
    scheduled:
      enabled: false
    sampler:
      percentage: 1.0
mail:
  host: smtp.163.com
  port: 25
  send:
    username: 13187325476@163.com
    password: 601124052zyzy
password:
  reset:
    url: http://oauth.cloud.saas.hand-china.com/password/
