spring:
  datasource:
    url: jdbc:mysql://192.168.12.95:3307/hap_user_service?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: hapcloud
    password: handhand
  rabbitmq:
    host: 192.168.12.95
    port: 5672
  redis:
    host: 192.168.12.95
    port: 6377
  cloud:
    config:
      allowOverride: true
      failFast: true
      overrideNone: false
      overrideSystemProperties: false
  sleuth:
    integration:
      enabled: false
    scheduled:
      enabled: false
    sampler:
      percentage: 1.0
