spring:
  datasource:
    url: jdbc:mysql://192.168.12.95:3307/hap_user_service?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: hapcloud
    password: handhand
  rabbitmq:
    host: 192.168.12.95
    port: 5672
  cloud:
    config:
      allowOverride: true
      failFast: true
      overrideNone: false
      overrideSystemProperties: false
  sleuth:
    integration:
      enabled: false
    scheduled:
      enabled: false
    sampler:
      percentage: 1.0
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 6000
zuul:
  addHostHeader: true
  routes:
    hbcContract:
      path: /contract/**
      serviceId: hbc-contract-service
    hbc:
      path: /blockchain/**
      serviceId: hbc-blockchain-service
    hbcNode:
      path: /node/**
      serviceId: hbc-node-service
    hbcClient:
      path: /blockchain-client/**
      serviceId: hbc-blockchain-client-service
    hbcFileTransfer:
      path: /blockchain-file-tranfer/**
      serviceId: hbc-file-transfer-service
    hbcClientTest:
      path: /blockchain-client-second/**
      serviceId: hbc-blockchain-client-service-second
    hbcDappSupperVendor:
      path: /blockchain-dsv/**
      serviceId: hbc-dsv-service
    uaa:
      path: /uaa/**
      serviceId: hap-user-service
    fws:
      path: /fws/**
      serviceId: hap-framework-service
    admin:
      path: /admin/**
      serviceId: hap-user-admin-service
    deployment:
      path: /deployment/**
      serviceId: hap-deployment-service
    deploymentAdmin:
      path: /deploymentAdmin/**
      serviceId: hap-deployment-admin-service
    enterprise:
      path: /enterprise/**
      serviceId: hap-enterprise-service
    oauth:
      path: /oauth/**
      sensitiveHeaders:
      serviceId: hap-oauth-server
      stripPrefix: false
security:
  oauth2:
    resource:
      userInfoUri: http://hap-oauth-server/oauth/api/user
  ignored:
    - /oauth/**
swagger:
  oauthUrl: http://localhost:8080/oauth/oauth/authorize
hap:
  permission:
    service:
      check: false
