spring:
  datasource:
    url: jdbc:mysql://192.168.12.95:3307/hbc_blockchain_service?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: hapcloud
    password: handhand
  rabbitmq:
    host: 192.168.12.95
    port: 5672
    exchange: hbc
    exchangeType: topic
  cloud:
    config:
      allowOverride: true
      failFast: true
      overrideNone: false
      overrideSystemProperties: false
  sleuth:
    integration:
      enabled: false
    scheduled:
      enabled: false
    sampler:
      percentage: 1.0
serviceAccountId: 0

network:
  rediscache:
    cacheSeconds: 600
  time:
    count: 100
    period: 2000
    delay: 1000
  project:
    namespace: hbc