spring:
  datasource:
    url: jdbc:mysql://192.168.12.95:3307/hap_scheduler_service?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: hapcloud
    password: handhand
  redis:
    host: 192.168.12.95
    port: 6377
  rabbitmq:
    host: 192.168.12.95
    port: 5672

swagger:
  oauthUrl: http://localhost:8080/oauth/oauth/authorize
