spring:
  datasource:
    url: jdbc:mysql://192.168.12.134:3306/hap_scheduler_service?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: hbcprod369753
  redis:
    host: 192.168.12.134
    port: 6379
  rabbitmq:
    host: 192.168.12.134
    port: 5672

swagger:
  oauthUrl: http://localhost:8080/oauth/oauth/authorize
