spring:
  datasource:
    url: jdbc:mysql://192.168.12.134:3306/hap_zipkin_ui?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: hbcprod369753
    schema: classpath:/mysql.sql
    initialize: true
    continueOnError: true