spring:
  datasource:
    url: jdbc:mysql://192.168.12.134:3306/hap_user_service?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: hbcprod369753
  rabbitmq:
    host: 192.168.12.134
    port: 5672
  cloud:
    config:
      allowOverride: true
      failFast: true
      overrideNone: false
      overrideSystemProperties: false
  sleuth:
    integration:
      enabled: false
    scheduled:
      enabled: false
    sampler:
      percentage: 1.0
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000
 
zuul:
  addHostHeader: true
  max:
    host:
      connections: 500
      socket-timeout-millis: 60000
      connect-timeout-millis: 60000
  routes:
    hbcNode:
      path: /node/**
      serviceId: hbc-node-service
    hbcK8s:
      path: /k8s/**
      serviceId: hbc-k8s-service
    hbcExplorer:
      path: /explorer/**
      serviceId: hbc-explorer-service
    hbcSupplyChain:
      path: /supplychain/**
      serviceId: hbc-supplychain-service
    hbcContract:
      path: /contract/**
      serviceId: hbc-smart-contract-service
    hbc:
      path: /blockchain/**
      serviceId: hbc-blockchain-service
    hbcNode:
      path: /rancher/**
      serviceId: hbc-rancher-service
    hbcClient:
      path: /blockchain-client/**
      serviceId: hbc-blockchain-client-service
    hbcFileTransfer:
      path: /blockchain-file-tranfer/**
      serviceId: hbc-file-transfer-service
    hbcClientTest:
      path: /blockchain-client-second/**
      serviceId: hbc-blockchain-client-service-second
    hbcDappSupperVendor:
      path: /blockchain-dsv/**
      serviceId: hbc-dsv-service
    uaa:
      path: /uaa/**
      serviceId: hap-user-service
    fws:
      path: /fws/**
      serviceId: hap-framework-service
    admin:
      path: /admin/**
      serviceId: hap-user-admin-service
    deployment:
      path: /deployment/**
      serviceId: hap-deployment-service
    deploymentAdmin:
      path: /deploymentAdmin/**
      serviceId: hap-deployment-admin-service
    enterprise:
      path: /enterprise/**
      serviceId: hap-enterprise-service
    oauth:
      path: /oauth/**
      sensitiveHeaders:
      serviceId: hap-oauth-server
      stripPrefix: false
security:
  oauth2:
    resource:
      userInfoUri: http://hap-oauth-server/oauth/api/user
  ignored:
    - /oauth/**
swagger:
  oauthUrl: http://localhost:8080/oauth/oauth/authorize
hap:
  permission:
    service:
      check: false
