spring:
  datasource:
    url: jdbc:mysql://192.168.12.134:3306/hbc_blockchain_service?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: hbcprod369753
  rabbitmq:
    host: 192.168.12.134
    port: 5672
  cloud:
    config:
      allowOverride: true
      failFast: true
      overrideNone: false
      overrideSystemProperties: false
  sleuth:
    integration:
      enabled: false
    scheduled:
      enabled: false
    sampler:
      percentage: 1.0

docker:
  image:
    IMAGE_NODESDK: registry.choerodon.com.cn/mobile-center-handblockchain/hbc-fabric:dev
    IMAGE_HBC_CA_API_SERVER: registry.choerodon.com.cn/mobile-center-handblockchain/hbc-ca-api-server:dev
    IMAGE_SIDECAR: registry.choerodon.com.cn/mobile-center-handblockchain/hbc-blockchain-client-service:v1.0
    IMAGE_PEER: hyperledger/fabric-peer:x86_64-1.1.0
    IMAGE_ORDERER: hyperledger/fabric-orderer:x86_64-1.1.0
    IMAGE_FABRIC_CA: hyperledger/fabric-ca:x86_64-1.1.0
    IMAGE_ZK: hyperledger/fabric-zookeeper:x86_64-0.4.6
    IMAGE_KAFKA: hyperledger/fabric-kafka:x86_64-0.4.6
    IMAGE_COUCHDB: hyperledger/fabric-couchdb:x86_64-0.4.6
    
kubernetes:
  namespace: hbc