spring:
  datasource:
    url: jdbc:mysql://mysql/hap_scheduler_service?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: hapcloud
    password: handhand
  redis:
    host: redis
    port: 6379
  rabbitmq:
    host: rabbitmq
    port: 5672

swagger:
  oauthUrl: http://localhost:8080/oauth/oauth/authorize
