spring:
  datasource:
    url: jdbc:mysql://mysql/hap_event_service?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: hapcloud
    password: handhand
  rabbitmq:
    host: rabbitmq
    port: 5672
  cloud:
    config:
      allowOverride: true
      failFast: true
      overrideNone: false
      overrideSystemProperties: false
