spring:
  datasource:
    url: jdbc:mysql://hapcloudmysql.db.svc/hap_framework_service?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: hapcloud
    password: handhand
  rabbitmq:
    host: rabbitmq
    port: 5672
  cloud:
    config:
      allowOverride: true
      failFast: true
      overrideNone: false
      overrideSystemProperties: false
  sleuth:
    integration:
      enabled: false
    scheduled:
      enabled: false
    sampler:
      percentage: 1.0
swagger:
  oauthUrl: http://oauth.cloud.saas.hand-china.com/oauth/authorize
