spring:
  datasource:
    url: jdbc:mysql://hapcloudmysql.db.svc/hap_user_service?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: hapcloud
    password: handhand
  rabbitmq:
    host: rabbitmq
    port: 5672
  cloud:
    config:
      allowOverride: true
      failFast: true
      overrideNone: false
      overrideSystemProperties: false
  sleuth:
    integration:
      enabled: false
    scheduled:
      enabled: false
    sampler:
      percentage: 1.0
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: false
ribbon:
  ReadTimeout: 100000
  ConnectTimeout: 100000 
zuul:
  addHostHeader: true
  routes:
    uaa:
      path: /uaa/**
      serviceId: hap-user-service
    fws:
      path: /fws/**
      serviceId: hap-framework-service
    admin:
      path: /admin/**
      serviceId: hap-user-admin-service
    deployment:
      path: /deployment/**
      serviceId: hap-deployment-service
    deploymentAdmin:
      path: /deploymentAdmin/**
      serviceId: hap-deployment-admin-service
    enterprise:
      path: /enterprise/**
      serviceId: hap-enterprise-service
    oauth:
      path: /oauth/**
      sensitiveHeaders:
      serviceId: hap-oauth-server
      stripPrefix: false
  ws:
    brokerages:
      deployment:
        end-points: /hapcloud-websocket
        brokers:  /topic
        destination-prefixes: /app
security:
  oauth2:
    resource:
      userInfoUri: http://hap-oauth-server/oauth/api/user
  ignored:
    - /oauth/**
swagger:
  oauthUrl: http://gateway.hapcloud.stage.cloud.saas.hand-china.com/oauth/oauth/authorize
hap:
  permission:
    service:
      check: false
